### PR TITLE
add document build and deploy jobs

### PR DESCRIPTION
**Pull request by SimeonEhrig**
solves #10 

Copy of: https://github.com/QEDjl-project/QEDevents.jl/pull/10

### CODE REVIEW

**Comment by SimeonEhrig** [comment]
> I will look into this. I assume some API change in `Documenter.jl`.

Looks like this line of code causes the problem: https://github.com/QEDjl-project/QEDprocesses.jl/blob/0074aa02285d5ef39e63f5a204e02ac4b5b1f6d8/src/interfaces/setup_interface.jl#L101

**Comment by SimeonEhrig** [comment]
> > I will look into this. I assume some API change in `Documenter.jl`.
> 
> Looks like this line of code causes the problem:
> 
> https://github.com/QEDjl-project/QEDprocesses.jl/blob/0074aa02285d5ef39e63f5a204e02ac4b5b1f6d8/src/interfaces/setup_interface.jl#L101

@szabo137 Looks like, the documentation references an error type, which does not exist. I didn't found anything in the QED projects and also not in the official documentation.

**Comment by AntonReinhard** [comment]
It should be `AbstractInvalidInputException`, that's what is defined. But it is a little weird that one is `SomethingException` and the other is `SomethingError`, so we should probably use one of the two consistently everywhere. I think I would prefer `Exception`,  `Error` is less specific.

**Comment by SimeonEhrig** [comment]
> It should be `AbstractInvalidInputException`, that's what is defined. But it is a little weird that one is `SomethingException` and the other is `SomethingError`, so we should probably use one of the two consistently everywhere. I think I would prefer `Exception`, `Error` is less specific.
> 
> So I'd suggest renaming the `InvalidInputError` to `InvalidInputException`, too.

Yes, you are right. We are a little bit inconsistent :sweat_smile: 

https://github.com/QEDjl-project/QEDprocesses.jl/blob/0074aa02285d5ef39e63f5a204e02ac4b5b1f6d8/src/interfaces/setup_interface.jl#L79-L83

Nevertheless, I would fix the error in the documentation now and we do the possible renaming in an extra PR.

**Review by szabo137 — APPROVED** [review]
Nothing to bother, merging!

**Pull request merged**
