### PR TITLE
Remove abstract cs and probability implementations

### PR DESCRIPTION
**Pull request by AntonReinhard**
The implementations of the cross sections and probability functions for abstract processes have moved to QEDbase, see https://github.com/QEDjl-project/QEDbase.jl/pull/87. They are therefore now deleted here.

Fixes issue https://github.com/QEDjl-project/QEDbase.jl/issues/86

### CODE REVIEW

**Review by szabo137 — DISMISSED** [review]
Thanks for the fast PR! Looks good for me. Will merge if the pipeline succeeds.

**Comment by AntonReinhard** [comment]
> Thanks for the fast PR! Looks good for me. Will merge if the pipeline succeeds.
> 
> Edit: Oh, the tests, you are right 😅

Yes, almost forgot :sweat_smile: Should be good if the pipeline goes through  :+1: 
Feel free to merge then.

**Comment by AntonReinhard** [comment]
Something seems to break with the pipeline. It finds and clones the correct QEDbase version, but somehow there seems to be a git merge happening in the Project.toml, leading to a parsing error

**Comment by szabo137** [comment]
> Something seems to break with the pipeline. It finds and clones the correct QEDbase version, but somehow there seems to be a git merge happening in the Project.toml, leading to a parsing error

My bad, wrong commit hash 🤦‍♂️ 
This is the correct one: fb4c800acc99ffe83efe558a5a094e63eed9abde

**Comment by szabo137** [comment]
Please remove the CI_UNIT_PKG_URL_QEDbase from the last commit message and force push again.. this should use the current `QEDbase#dev` and therefore should pass the tests.

**Review by szabo137 — APPROVED** [review]

**Pull request merged**
