### PR TITLE
Remove interfaces and functionality that move

### PR DESCRIPTION
**Pull request by AntonReinhard**
The interfaces and functionality have moved to QEDbase and QEDcore.

### CODE REVIEW

**Comment by szabo137** [comment]
@AntonReinhard Please update QEDbase and push again. Whats needed to fix this?

**Comment by AntonReinhard** [comment]
> @AntonReinhard Please update QEDbase and push again. What's needed to fix this?
> 
> Edit: Seems like QEDbase-compat is broken. Maybe rebasing would be good :)

This needs to be merged: https://github.com/QEDjl-project/QEDcore.jl/pull/25 and QEDcore needs to be released. The implementations of PhaseSpacePoint for example move there but aren't yet available.

**Comment by AntonReinhard** [comment]
Also, the `QEDbase.` replacements in QEDcore need to be removed again I think.

**Comment by AntonReinhard** [comment]
This builds and tests locally with the changes from https://github.com/QEDjl-project/QEDcore.jl/pull/29 and the dev-branch of QEDbase.

**Comment by AntonReinhard** [comment]
> The doc building fails because for some reason it refuses to get QEDbase 0.2 instead of 0.1. I have no idea why.

I found the problem. Should be ready for review now. @szabo137 ping

**Review by szabo137 — APPROVED** [review]
LGFM. In a separate PR, we should remove the implementations of `differential_probability`, `total_probability` and  `differential_cross_section`, `total_cross_section`, because we add them to `QEDbase`: https://github.com/QEDjl-project/QEDbase.jl/pull/87

**Pull request merged**
