### PR TITLE
bumped compat entry for QEDbase

### PR DESCRIPTION
**Pull request by szabo137**
CI_INTG_PKG_URL_QEDcore=https://github.com/szabo137/QEDcore.jl#bump-QEDbase-compat

- [ ] check if https://github.com/QEDjl-project/QEDcore.jl/pull/78 is merged

### CODE REVIEW

**Comment by szabo137** [comment]
This is based on https://github.com/QEDjl-project/QEDcore.jl/pull/78; consider merging this after the former is merged.

**Comment by szabo137** [comment]
docs build locally against https://github.com/szabo137/QEDcore.jl#bump-QEDbase-compat, therefore, consider merging, if https://github.com/QEDjl-project/QEDcore.jl/pull/78 is merged **and** released.

**Comment by SimeonEhrig** [comment]
@szabo137 please rebase

**Comment by AntonReinhard** [comment]
I think with #106 this can now be closed

**Comment by SimeonEhrig** [comment]
The PR also introduce a compat section in the `docs/Project.toml`. Is this something which we want to do?

**Comment by AntonReinhard** [comment]
> The PR also introduce a compat section in the `docs/Project.toml`. Is this something which we want to do?

Good question, I don't know if it's necessary?

**Comment by szabo137** [comment]
I tried to solve the compat problem for docs building by introducing the compat section in `docs/Project.toml`. However, I guess this is no longer necessary with the fixed from you. 

Therefore, I close this.

**Pull request closed without merging**
